[phases.setup]
nixPkgs = [
    "php83", 
    "php83Packages.composer", 
    "php83Extensions.pdo", 
    "php83Extensions.sqlite3",
    "php83Extensions.mbstring",
    "php83Extensions.xml",
    "php83Extensions.ctype"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

# قمنا بإزالة أمر php artisan config:cache لأنه هو الذي يسبب الانهيار حالياً
[phases.build]
cmds = []

# تشغيل التطبيق مباشرة مع السماح بالوصول للملفات
[start]
cmd = "php -S 0.0.0.0:${PORT} -t public"